// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD6naRHstXVWWrjexU8dgbFyBGtoi0rB0',
    appId: '1:285130655520:web:451ad8f937823c3a4b7945',
    messagingSenderId: '285130655520',
    projectId: 'red-sosia',
    authDomain: 'red-sosia.firebaseapp.com',
    storageBucket: 'red-sosia.firebasestorage.app',
    measurementId: 'G-D7NM6FPS7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB1KYI3X8pdX2thunvJH9UeCBXeP9bgmA',
    appId: '1:285130655520:android:e0c524cd8592cb3e4b7945',
    messagingSenderId: '285130655520',
    projectId: 'red-sosia',
    storageBucket: 'red-sosia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqhmfWllXzXobYGsGns6oybypobspudSQ',
    appId: '1:285130655520:ios:6ecf318c0e95cff74b7945',
    messagingSenderId: '285130655520',
    projectId: 'red-sosia',
    storageBucket: 'red-sosia.firebasestorage.app',
    iosBundleId: 'com.example.redSosia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqhmfWllXzXobYGsGns6oybypobspudSQ',
    appId: '1:285130655520:ios:6ecf318c0e95cff74b7945',
    messagingSenderId: '285130655520',
    projectId: 'red-sosia',
    storageBucket: 'red-sosia.firebasestorage.app',
    iosBundleId: 'com.example.redSosia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDD6naRHstXVWWrjexU8dgbFyBGtoi0rB0',
    appId: '1:285130655520:web:9b78f2f64af026aa4b7945',
    messagingSenderId: '285130655520',
    projectId: 'red-sosia',
    authDomain: 'red-sosia.firebaseapp.com',
    storageBucket: 'red-sosia.firebasestorage.app',
    measurementId: 'G-TBM6NER4YH',
  );

}